apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-youtubedl
  namespace: default
spec:
  secretName: letsencrypt-youtubedl
  dnsNames:
    - yt.sbb.org
  issuerRef:
    name: letsencrypt-youtubedl
    kind: ClusterIssuer