apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: youtubedl
  namespace: default
spec:
  secretName: youtubedl
  dnsNames:
    - yt.sbb.org
  issuerRef:
    name: youtubedl
    kind: ClusterIssuer