apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-youtube-dl
  namespace: default
spec:
  secretName: letsencrypt-youtube-dl
  dnsNames:
    - yt.sbb.org
  issuerRef:
    name: letsencrypt-youtube-dl
    kind: ClusterIssuer