apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-youtubedl
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wiechert@fachadmin.de
    privateKeySecretRef:
      name: letsencrypt-youtubedl
    solvers:
      - http01:
          ingress:
            class: youtubedl # muss spec.ingressClassName entsprechen