apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
        - name: pihole
          image: pihole/pihole
          ports:
            - containerPort: 80
              name: pihole
          env:
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-mysql-secret
                  key: WEBPASSWORD
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  WEBPASSWORD: U3VwZXJTZWNyZXQK

---
kind: Service
apiVersion: v1
metadata:
  name: pihole-service
spec:
  type: ClusterIP
  selector:
    app: pihole
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  annotations:
    spec.ingressClassName: pihole
    cert-manager.io/cluster-issuer: letsencrypt-pihole # must match cert/clusterissuer.yaml metadata.name
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: pihole
  rules:
    - host: pi.sbb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  pihole-service
                port:
                  number: 80
  tls:
    - hosts:
        - pi.sbb.org
      secretName: letsencrypt-pihole

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: pihole
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx