apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud
#          securityContext:
#            runAsUser: 1000    # UID des Verzeichnisses
#            runAsGroup: 1000   # GID des Verzeichnisses
          ports:
            - containerPort: 80
              name: nextcloud
          volumeMounts:
            - name: nextcloud-data
              mountPath: /var/www/html
            - name: backup-volume
              mountPath: /backup
          env:
            - name: MYSQL_HOST
              value: nextcloud-mysql-service.default.svc.cluster.local
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-mysql-secret
                  key: MARIADB_ROOT_PASSWORD
            - name: MYSQL_USER
              value: root
            - name: MYSQL_DATABASE
              value: nextcloud-mysql
            - name: NEXTCLOUD_ADMIN_USER
              value: alex
            - name: NEXTCLOUD_ADMIN_PASSWORD
              value: SuperSecret
            - name: REDIS_HOST
              value: redis.default.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
            - name: PHP_MEMORY_LIMIT
              value: 512M
            - name: PHP_UPLOAD_LIMIT
              value: 512M

      volumes:
        - name: nextcloud-data
          persistentVolumeClaim:
            claimName: nextcloud-pvc
        - name: backup-volume
          hostPath:
            path: /home/awiechert/backup/nextcloud/alex  # Pfad auf der Node
            type: Directory
---
kind: Service
apiVersion: v1
metadata:
  name: nextcloud-service
spec:
  type: ClusterIP
  selector:
    app: nextcloud
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nextcloud-pv
spec:
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /srv/data/nextcloud

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: manual

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud
  annotations:
    nginx.ingress.kubernetes.io/hsts: "true"
    nginx.ingress.kubernetes.io/hsts-max-age: "15552000" # 6 Monate
    nginx.ingress.kubernetes.io/hsts-include-subdomains: "true"
    nginx.ingress.kubernetes.io/hsts-preload: "true"
    nginx.ingress.kubernetes.io/proxy-set-headers: "nextcloud-headers"
    cert-manager.io/cluster-issuer: letsencrypt-prod # must match cert/clusterissuer.yaml metadata.name
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
spec:
  ingressClassName: nginx
  rules:
    - host: nc.sbb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  nextcloud-service
                port:
                  number: 80
  tls:
    - hosts:
        - nc.sbb.org
      secretName: letsencrypt-prod-secret

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nextcloud-headers
  namespace: default
data:
  X-Forwarded-For: $proxy_add_x_forwarded_for
  X-Real-IP: $remote_addr
  X-Forwarded-Proto: $scheme
