apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-wordpress
  namespace: default
spec:
  secretName: letsencrypt-wordpress
  dnsNames:
    - www.sbb.org
  issuerRef:
    name: letsencrypt-wordpress
    kind: ClusterIssuer