apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-cert
  namespace: default
spec:
  secretName: letsencrypt-prod-secret
  duration: 8760h # 365 Tage
  renewBefore: 360h # 15 Tage vor Ablauf erneuern
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: nc.sbb.org
  dnsNames:
    - nc.sbb.org