apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wiechert@fachadmin.de
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          route53:
            region: eu-central-1
            hostedZoneID: Z02578323K2R3NEUM5KAE
            accessKeyIDSecretRef:
              name: route53-credentials-secret
              key: accessKeyID
            secretAccessKeySecretRef:
              name: route53-credentials-secret
              key: secretAccessKey


