apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-pihole
  namespace: default
spec:
  secretName: letsencrypt-pihole
  dnsNames:
    - pi.sbb.org
  issuerRef:
    name: letsencrypt-pihole
    kind: ClusterIssuer