apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-prod-cert
  namespace: default
spec:
  secretName: letsencrypt-prod-secret
  dnsNames:
    - pi.sbb.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer