apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-pihole
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wiechert@fachadmin.de
    privateKeySecretRef:
      name: letsencrypt-pihole
    solvers:
      - http01:
          ingress:
            class: nginx # muss spec.ingressClassName entsprechen