apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubedl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtubedl
  template:
    metadata:
      labels:
        app: youtubedl
    spec:
      containers:
        - name: youtubedl
          image: kmb32123/youtube-dl-server
          ports:
            - containerPort: 8080
              name: youtubedl


---
kind: Service
apiVersion: v1
metadata:
  name: youtubedl-service
spec:
  type: ClusterIP
  selector:
    app: youtubedl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtubedl
  annotations:
    spec.ingressClassName: youtubedl
    cert-manager.io/cluster-issuer: letsencrypt-youtubedl # must match cert/clusterissuer.yaml metadata.name
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: yt.sbb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  youtubedl-service
                port:
                  number: 80
  tls:
    - hosts:
        - yt.sbb.org
      secretName: letsencrypt-youtubedl

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: youtubedl
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

