apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtubedl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtubedl
  template:
    metadata:
      labels:
        app: youtubedl
    spec:
      containers:
        - name: youtubedl
          image: youtubedl/youtubedl
          ports:
            - containerPort: 80
              name: youtubedl
          env:
            - name: WEBPASSWORD
              valueFrom:
                secretKeyRef:
                  name: youtubedl-admin
                  key: WEBPASSWORD

---
kind: Service
apiVersion: v1
metadata:
  name: youtubedl-service
spec:
  type: ClusterIP
  selector:
    app: youtubedl
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: youtubedl
  annotations:
    spec.ingressClassName: youtubedl
    cert-manager.io/cluster-issuer: letsencrypt-youtubedl # must match cert/clusterissuer.yaml metadata.name
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: youtubedl
  rules:
    - host: pi.sbb.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name:  youtubedl-service
                port:
                  number: 80
  tls:
    - hosts:
        - pi.sbb.org
      secretName: letsencrypt-youtubedl

---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: youtubedl
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx

