apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: git@github.com:AlexanderWiechert/k3s-playground.git
    targetRevision: HEAD
    path: kustomize/base
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
